### ISSUE TITLE
RTIC Scope licenses

### ISSUE THREAD

**Issue by tmplt** [rtic-scope/rfcs#1]
We have yet to settle completely on how to license RTIC Scope. After some initial internal discussion the tracing-related libraries (itm-decode, rtic-trace) will be licensed under what is common for Rust project (Apache 2.0 OR MIT).

The RTIC Scope back- and frontends, being the key components of the project, we want to license in a way so that non-commercial use is free (as in free beer), libre, OSS, etc. But commercial use should be licensed in a way so that the project developer's can make bread on their contributions, be it via some parent company, or free-lance. I believe this summarizes our thoughts this far.

Requesting your input, @Yatekii, @perlindgren.

**Comment by tmplt** [comment]
Topical reading:
- https://opensource.stackexchange.com/questions/5599/any-successful-dual-license-oss-project-i-can-use-as-template (I believe that "if you want to embed it in some proprietary solution, you pay" is what we want in a nutshell)
- https://opensource.stackexchange.com/questions/8891/dual-license-open-source-software/8894#8894
- http://oss-watch.ac.uk/resources/duallicence2

There is some suggestion that we need contributors to sign a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) so that all source code is owned by a single entity. This allegedly simplifies dual-licensing a lot (because we do not need to ask individual contributors if they are okay with licensing their contributions in some specific way), and I believe that contracts will be drafted in an adhoc manner. However, the introduction of a CLA will be a great hurdle if we want to attract contributors. I believe a CLA would hurt the project more than help it.

And of course, a bad commercial actor will just disregard whatever licenses we have and use the code anyway.

Whatever licenses we end up on, it should not introduce any hurdles for OSS contributors.

**Comment by perlindgren** [comment]
I don't think CLA is what we are looking for.
/Per

**Comment by tmplt** [comment]
Licences has now been set for all repositories except `cargo-rtic-scope`.

**Comment by tmplt** [comment]
[SQLite's approach](https://sqlite.org/purchase/license) is worth a read.

**Comment by tmplt** [comment]
It has been decided that all RTIC Scope repos/crates will be licensed under MIT/Apache 2.0 for non-commercial ends. If commercial support is wanted in any capacity, or if a commercial actor wants to license the software differently, they are to contact @grepitab.
